# Generated by Django 4.0.3 on 2023-01-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pickup',
        ),
    ]
