# Generated by Django 4.0.3 on 2023-01-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.CharField(max_length=255)),
                ('pickup_time', models.CharField(max_length=255)),
            ],
        ),
    ]
