# Generated by Django 4.0.3 on 2023-01-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pickup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='c_name',
            new_name='c_fname',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='c_lname',
            field=models.CharField(default='lastname', max_length=30),
            preserve_default=False,
        ),
    ]
