# Generated by Django 4.0.3 on 2023-01-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_c_name_customerprofile_c_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='c_fname',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='c_lname',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='c_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
