# Generated by Django 4.0.3 on 2023-01-17 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_customerprofile_c_fname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='CNIC',
            field=models.CharField(default='42101-4250287-7', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='static/assets/profile_img/'),
        ),
        migrations.AddField(
            model_name='user',
            name='t_physical_shop_address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='TailorProfile',
        ),
    ]
