# Generated by Django 4.0.3 on 2023-01-17 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_tailorprofile_user_user_cnic_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
